name: Deploy Swagger UI to Github Pages

on:
  push:
    branches:
      - develop
      - open-api
  pull_request:
    branches:
      - main
      - develop
    types:
      - opened
      - synchronize
      - closed
    paths:
      - docs/api/openapi.yaml
      - .github/workflows/deploy-swagger.yaml

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install swagger-cli
        run: |
          npm install -g swagger-cli

      - name: Validate Swagger Files
        run: |
          swagger-cli validate -d docs/api/openapi.yaml --type yaml

      - name: Generate Swagger UI
        if: github.event.pull_request.merged == true
        uses: Legion2/swagger-ui-action@v1
        with:
          output: swagger-ui
          spec-file: docs/api/openapi.yaml

      - name: Deploy to GitHub Pages
        if: github.event.pull_request.merged == true
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: swagger-ui